---

- name: Install Docker
  yum:
    name=docker
    state=present

- name: Start Docker Service
  service:
    name=docker
    state=running
    enabled=yes

- name: Create Docker Registry Mount Directory
  file:
    path=/opt/docker-registry
    state=directory

- name: Copy Registry Config File
  template:
    src=registry-conf.yml.j2
    dest=/opt/docker-registry/registry-conf.yml

- name: application container
  docker:
    name: registry
    image: registry
    state: reloaded
    pull: always
    ports:
    - "5000:5000"
    env:
      SETTINGS_FLAVOR: s3
      AWS_BUCKET: lunch-learn-docker
      STORAGE_PATH: /registry
      AWS_KEY: AKIAJYBBQTD72ZH3UPRA
      AWS_SECRET: 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
      STORAGE_REDIRECT: true
      AWS_REGION: us-west-2
